### ISSUE TITLE
iOS CarouselView change item template crash

### ISSUE THREAD

**Issue by CorentinSwiss4** [AndreiMisiukevich/CardView.MAUI#11]
I would like to display syncfusion shimmer until load data in carousel view and change item template after but there is a crash when i change item template and change swipe to right item swipe to left and swipe again to right item.

"Unable to convert Microsoft.Maui.Handlers.ContentViewHandler to UIKit.UIView"

if i switch to use the maui carousel view it's work fine.

CardsView.Maui 0.0.4
I use .net 7
Maui 
syncfusion 21.2.10

stack trace : 

`Microsoft.Maui.ElementHandlerExtensions.ToPlatform(IElementHandler elementHandler)
Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect)
Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].PlatformArrange(Rect rect)
Microsoft.Maui.Controls.Compatibility.Platform.iOS.HandlerToRendererShim.OnBatchCommitted(Object sender, EventArg`1 e)
Microsoft.Maui.Controls.VisualElement.BatchCommit()
PanCardView.Processors.CarouselProcessor.SetTranslationX(View view, Double value, CardsView cardsView, Boolean isFront, Nullable`1 isVisible, Boolean isClean)
PanCardView.Processors.CarouselProcessor.Clean(CardsView cardsView, ProcessorItem[] items)
PanCardView.CardsView.CleanView(View view)
PanCardView.CardsView.RemoveChildren(IView[] views)
PanCardView.CardsView.<>c__DisplayClass332_0.<RemoveRedundantChildren>b__0()
PanCardView.CardsView.InvokeOnMainThreadIfNeeded(Action action)
PanCardView.CardsView.RemoveRedundantChildren(Boolean isProcessingNow)
PanCardView.CardsView.CompleteInteraction(Boolean isProcessingNow, Boolean isNewItemSelected)
PanCardView.CardsView.OnTouchEnded()
System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
Foundation.NSAsyncSynchronizationContextDispatcher.Apply()
UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)

**Comment by AndreiMisiukevich** [comment]
Hi @CorentinSwiss4 
Hmm, really no idea why it happens. Would you like to debug it and submit a PR with fix?

**Comment by CorentinSwiss4** [comment]
I Can try to solve it as soon as possible.

**Comment by CorentinSwiss4** [comment]
[edit] issue it's not just with syncfusion shimmer it's changing itemtemplate in current execution, i continue to work on this

**Comment by AndreiMisiukevich** [comment]
@CorentinSwiss4 that's for keeping me posted 👍 
To be honest, I suspect it can some issue with wrong views/renderers inheritance.

But.. hell... it's so unclear how to implement it properly. I gave up.

**Comment by eyeveye** [comment]
Suspect is your syntax. <ViewCell>

**Comment by eyeveye** [comment]
> Suspect is your syntax.
ViewCell

**Comment by wollfoDream** [comment]
Any workaround for this?

**Comment by riccardomartins** [comment]
Also happening for me, anyone has a fix for this?

**Comment by AndreiMisiukevich** [comment]
As a workaround (potentially, as I didn't test it)
you can try completely replacing one carousel with another (Using code-behind).
Also, you try to put two carousels on your page and change one to another using the `IsVisible` property.

**Comment by AndreiMisiukevich** [comment]
maybe 0.0.5 fixes it
