### ISSUE TITLE
Swipe gesture overlays horizontal collection view scroll

### ISSUE THREAD

**Issue by angelspid** [AndreiMisiukevich/CardView.MAUI#12]
I include a some collection views with horizontal scroll  in Carousel view but when I try to scroll CV carusell view change a page.

**Comment by AndreiMisiukevich** [comment]
:) Yes
How can we determine whether a user wants to scroll a carousel or collection view?

**Comment by angelspid** [comment]
I agree. But this happened only on Android,  on iOS is OK everything.

**Comment by AndreiMisiukevich** [comment]
Hmm, you can try to set `ShouldThrottlePanInteraction = true`
Or maybe set `ElementThresholdDistance = 20`
But I am not sure it would help

**Comment by angelspid** [comment]
It's fixed by adding  MoveThresholdDistance="100" to CoverFlowView.

**Comment by angelspid** [comment]
It's fixed by adding MoveThresholdDistance="100" to CoverFlowView.
