### ISSUE TITLE
Just wondering if Windows is supported

### ISSUE THREAD

**Issue by cleanshaven** [AndreiMisiukevich/CardView.MAUI#13]
Not an issue but a question, Is Windows supported by this package.  The Android version of my project work fine with CardView.Maui however when I build for windows I get a blank spot where my card stack should be.

Sorry for using the issues for this question but I did not know where I could ask this question.

**Comment by AndreiMisiukevich** [comment]
Hi @cleanshaven no worries :) All is fine
TBH, I thought it worked

**Comment by AndreiMisiukevich** [comment]
Could you please try to download source code and debug it? (as I am a mac user)
