### ISSUE TITLE
[Early report] .NET 8.0 the all views is invisible

### ISSUE THREAD

**Issue by angelspid** [AndreiMisiukevich/CardView.MAUI#14]
Hello, 
Tested my application in .net 8 but. I use CoverFlowView for rendering different views like tabs on one page, using the itemsource with ObservableCollection<Views>. In .net7 everything is okay, works very well, but in .net 8 seems empty i try all types, and only gestures work.

**Comment by AndreiMisiukevich** [comment]
Hi @angelspid 
Sorry, I have lack of time for this project at this point.
Please feel free to debug it and submit a PR (If it's something related to this library rather than .NET 8 issue)

**Comment by AndreiMisiukevich** [comment]
duplicate https://github.com/AndreiMisiukevich/CardView.MAUI/issues/15
