### ISSUE TITLE
.net8 borders ItemTemplate doesn't show if it includes a border

### ISSUE THREAD

**Issue by Zack-G-I-T** [AndreiMisiukevich/CardView.MAUI#15]
The ItemTemplate shows blank in coverflow view when a border is used in the data template in .NET 8. 
Using a normal CarouselView works completely fine.

I have attatched the sample repo with frame replaced by border in PanCardViewSample.Views.CoverFlowSampleXamlView.
It also has a CarouselView abouve the CoverFlowView to compare.

https://github.com/Zack-G-I-T/MAUI.NET8.BorderIssue

**Comment by AndreiMisiukevich** [comment]
Hi Zack, please feel free to debu and submit a PR :)
And thanks for the report!
