### ISSUE TITLE
Remove compatibility dependencies

### ISSUE THREAD

**Issue by PureWeen** [AndreiMisiukevich/CardView.MAUI#16]
I noticed the renderers currently used the shimmed renderers

https://github.com/AndreiMisiukevich/CardView.MAUI/blob/6a0cef1657fe108c83be715cef86caa1408b3f6f/PanCardView/Platforms/iOS/CardsViewRenderer.cs#L16

Would it be possible to either

1) convert these to handlers
or
2) use these for your base classes instead https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Compatibility/Handlers/VisualElementRenderer.cs#L19 ? These are API symmetrical to VER but they are implemented via IViewHandler so they work a bit better with MAUI layout concepts. 

I think that might help with 
https://github.com/AndreiMisiukevich/CardView.MAUI/issues/15

**Comment by AndreiMisiukevich** [comment]
Hi Shane @PureWeen 
Unfortunately CardsView stops rendering when I switch to option (2)

<img width="538" alt="image" src="https://github.com/AndreiMisiukevich/CardView.MAUI/assets/10124814/a67d33c5-1640-427c-9ddd-428643efc4a2">
<img width="780" alt="image" src="https://github.com/AndreiMisiukevich/CardView.MAUI/assets/10124814/bd654a26-30c2-489b-8d70-29c8b310299f">


But if I comment out "AddHandler" in starts rendering again.

**Comment by AndreiMisiukevich** [comment]
That was exactly the reason why I had to use those renderers
What am I missing?

@PureWeen 

Thanks!
