### ISSUE TITLE
The handler's MauiContext cannot be null

### ISSUE THREAD

**Issue by riccardomartins** [AndreiMisiukevich/CardView.MAUI#18]
In iOS and Android everything works well, but in Windows I have this error everytime.
Could it be related to the Microsoft.Maui.Controls.Compatibility present in the CardsView? Is there something I could do to workaround this?

**Comment by AndreiMisiukevich** [comment]
Hi @riccardomartins 

It seems to be maui issue

https://github.com/dotnet/maui/issues/11600

**Comment by riccardomartins** [comment]
Thank you @AndreiMisiukevich
