### ISSUE TITLE
No Windows dll in Package lib

### ISSUE THREAD

**Issue by andy-waxman** [AndreiMisiukevich/CardView.MAUI#2]
Is there a reason why there is no Windows target lib in the nuget package?

'MauiAppBuilder' does not contain a definition for 'UseCardsView' and no accessible extension method 'UseCardsView' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?)	MauiCarousel (net7.0-windows10.0.19041.0)	

![image](https://user-images.githubusercontent.com/6384715/209853705-9d31b795-a91c-4b76-8d06-b6f347c863cf.png)

**Comment by AndreiMisiukevich** [comment]
Hmm
No idea honestly speaking
Probably we need to amend anything in pubspec, but I don't know because I use macOS on my laptop

**Comment by andy-waxman** [comment]
Line 5 of [PanCardView.csproj](https://github.com/AndreiMisiukevich/CardView.MAUI/blob/main/PanCardView/PanCardView.csproj) has a conditional for building on the windows platform.

**Comment by bcaceiro** [comment]
Hey, I have the same issue, the error is that is not available for windows :(

**Comment by andy-waxman** [comment]
Could you publish with GitHub Actions or some other cloud service?

**Comment by AndreiMisiukevich** [comment]
@andy-waxman good option

**Comment by mlancione** [comment]
I have successfully built and tested the library in Windows. I had to remove Maui compatibility mode which currently does not work in WinUI:

1. Remove UseMauiCompatibility()
2. Use the standard AbsoluteLayout in CardsView instead of Microsoft.Maui.Controls.Compatibility.AbsoluteLayout

**Comment by tinhmdxdev** [comment]
> @andy-waxman good option

Did you release this lib for the Windows version? Please! Thank you so much.

**Comment by AndreiMisiukevich** [comment]
@tinhmdxdev you can download the source code and run it on windows for now
I don't know when I will have time to manage this stuff

**Comment by tinhmdxdev** [comment]
> 

Okay. Let me try!

**Comment by tinhmdxdev** [comment]
> I have successfully built and tested the library in Windows. I had to remove Maui compatibility mode which currently does not work in WinUI:
> 
> 1. Remove UseMauiCompatibility()
> 2. Use the standard AbsoluteLayout in CardsView instead of Microsoft.Maui.Controls.Compatibility.AbsoluteLayout

Could you share the solution?

**Comment by tinhmdxdev** [comment]
> I have successfully built and tested the library in Windows. I had to remove Maui compatibility mode which currently does not work in WinUI:
> 
> 1. Remove UseMauiCompatibility()
> 2. Use the standard AbsoluteLayout in CardsView instead of Microsoft.Maui.Controls.Compatibility.AbsoluteLayout

@mlancione can you share the guideline to build this? I don't see any source code in Windows platform. I'm a newbie so I would be very grateful if you share it. Thank you.

**Comment by AndreiMisiukevich** [comment]
v0.0.4
