### ISSUE TITLE
Coverflow now gets squashed unless you set height request.

### ISSUE THREAD

**Issue by Zack-G-I-T** [AndreiMisiukevich/CardView.MAUI#20]
The last merge fixed issues with the border which is great @PavloLukianets! 

However, now the CoverFlowView doesn't measure what's inside it to determine height, so everything squashes into it.
In the samples project - If you change the grid back to a stackLayout in CoverFlowSampleXamlView.xaml you will see the CoverFlowView  get squashed to the top and the button renders over it as seen in the screenshot.

If you set a fixed height request it will work, however sometimes you don't always know what height the ItemTemplate is going to be.

![Screenshot_20231206-172240](https://github.com/AndreiMisiukevich/CardView.MAUI/assets/144355037/0589bc36-b432-4848-829b-4942850841bd)

**Comment by AndreiMisiukevich** [comment]
@PavloLukianets man, you did a great job so far. But... I am gonna leave this video here... :)

https://www.youtube.com/watch?v=fY7l2pcxdHM&ab_channel=BasketballAction

**Comment by themronion** [comment]
Yeah, you know i would just recommend to not use the legacy `Stacklayout` but i doubt its gonna be an acceptable solution)

**Comment by AndreiMisiukevich** [comment]
For some reason it doesn't work with Grid as well.
Pfff

**Comment by AndreiMisiukevich** [comment]
@themronion 

That's what I see (.NET 8, as far as I understand)
<img width="1353" alt="image" src="https://github.com/AndreiMisiukevich/CardView.MAUI/assets/10124814/1fe092c2-daa3-489a-9b26-eb21a8de2746">

**Comment by AndreiMisiukevich** [comment]
It can be just iOS MAUI bug though

**Comment by themronion** [comment]
Oh, well, haven't tested on ipad sim so dunno about that one

**Comment by vikern22** [comment]
Seeing similar(?) behavior on CarouselView on iOS. First is 0.0.4, second 0.0.5

![IMG_2199](https://github.com/AndreiMisiukevich/CardView.MAUI/assets/52527803/6b2ee83b-65b8-471a-9946-6c3450ab7d85)
![IMG_2200](https://github.com/AndreiMisiukevich/CardView.MAUI/assets/52527803/356b337e-8e7f-4909-9b4c-69ca65e3cf8d)

**Comment by AndreiMisiukevich** [comment]
@PavloLukianets do you have a desire to help with that stuff too? :)
It would be a grace from your side

**Comment by carlosxjose** [comment]
Great library and thanks for all your support!!!

I have the same issue... Rollback from 0.0.5 to 0.0.4 and everything is auto height again...

**Comment by riccardomartins** [comment]
We are having the same issue in CardsView

**Comment by PavloLukianets** [comment]
Jesus guys, why are u so lazy) Just fork the repo and do the fixes and open a pr. Here you are, cry-babies, try it out: 
[CardsView.Maui.0.0.6.nupkg.zip](https://github.com/AndreiMisiukevich/CardView.MAUI/files/13693126/CardsView.Maui.0.0.6.nupkg.zip)
