### ISSUE TITLE
CardsView : SlideShowDuration Binding

### ISSUE THREAD

**Issue by Lamghari** [AndreiMisiukevich/CardView.MAUI#22]
Hello,

I'm using CardsView to create a slide of images and videos. I would like to bind the **SlideShowDuration** value to the itemsSource elements.

This is my model :
``` c#
    public class MediaModel
    {
        public string Name { get; set; }
        public string MediaPath { get; set; }
        public string MediaType { get; set; }
        public string DisplayDuration { get; set; }
    }
```
This is my XAML :
``` XML
        <cards:CarouselView x:Name="carouselView" ItemsSource="{Binding Medias}"
                      SlideShowDuration="5000"
                      ItemTemplate="{StaticResource MediaSelector}">
                        . . .
        </cards:CarouselView>
```

I want **SlideShowDuration** to the take **DisplayDuration**'s value. I tried SlideShowDuration="{Binding DisplayDuration}" but it didn't work.

I would like some assistance if it's possible to apply this scenario or a workaround.

Thanks :)

**Comment by AndreiMisiukevich** [comment]
Hi @Lamghari 

In this case SlideShowDuration should be bound to CarouselView's current item.

You can try something like (not sure if MAUI allows binding property to the same view's one.

```xaml
SlideShowDuration="{Binding Source={x:Reference carouselView}, Path= SelectedItem.DisplayDuration}"
```


Also, keep in mind that DisplayDuration should be `int` (milliseconds)
