### ISSUE TITLE
cannot compile when datatemplate has databinding.

### ISSUE THREAD

**Issue by innomotionmedia** [AndreiMisiukevich/CardView.MAUI#23]
hello,

i am trying this:

        <cards:CarouselView >
            <cards:CarouselView.ItemsSource>
                <x:Array Type="{x:Type View}">
                    <StackLayout>
                        <CollectionView HorizontalOptions="FillAndExpand" ItemsSource="{Binding CollectionViewContent}">
                            <CollectionView.ItemTemplate>
                                <DataTemplate x:DataType="ViewModels:CollectionViewContent">
                                    <Grid Padding="10,6,10,6">
                                        <Grid.RowDefinitions>
                                            <RowDefinition Height="auto"/>
                                            <RowDefinition Height="2"/>
                                            <RowDefinition Height="auto"/>
                                        </Grid.RowDefinitions>
                                        <Label TextColor="{AppThemeBinding Dark=White, Default=Black}" HorizontalOptions="Start" FontSize="18" Text="{Binding PropertyName}"/>
                                        <BoxView Grid.Row="1" HeightRequest="2" BackgroundColor="{AppThemeBinding Dark=Black, Default=White}"/>
                                        <Label Margin="0,5,0,5" TextColor="{Binding Color}" FontFamily="WuerthExtraBold" HorizontalOptions="End" HorizontalTextAlignment="End" FontSize="22" Grid.Row="2" Text="{Binding PropertyValue}"/>
                                    </Grid>
                                </DataTemplate>
                            </CollectionView.ItemTemplate>
                        </CollectionView>
                    </StackLayout>
                    <StackLayout>
                        <Label Text="Hi yolonese"/>
                    </StackLayout>  
                </x:Array>
            </cards:CarouselView.ItemsSource>
        </cards:CarouselView>

What i want to achieve is a carouselview, that has different layouts in it. I populate the first stacklayout with real data and the second "yolonese" is just a placeholder.
I did get it to work when all layouts where static, but now that I bind to it, it wont compile and just throw an error saying: Value must not be null.

What can I do here?

**Comment by AndreiMisiukevich** [comment]
Consider using data template selector instead of x:Array of views
