### ISSUE TITLE
Weird behaviour when removing items from ItemsSource

### ISSUE THREAD

**Issue by dzebas** [AndreiMisiukevich/CardView.MAUI#24]
Hi,

Your amazing control works fine in Xamarin.Forms, but in Maui it behaves differently, hopefully you can give me some advice.

I use CarouselView to scroll the list of emails, but only keep 3 emails at one point - currently visible and one on the left and one on the right. Once you swipe to last one I add new to the end and delete first one, exactly opposite when going back. But in Maui when I delete first email CarouselView jumps to newly added one instead of staying on middle one.

The flow of event is as this:

1. Navigate to page with CarouselView
2. First email is loaded
3. Event "ItemAppeared" is triggered and second email is loaded
4. Swipe to second email
5. Event "ItemAppeared" is triggered again and third email is loaded
6. Swipe to third email
7. Event "ItemAppeared" is triggered again and fourth email is loaded
8. First email then gets deleted from the email list source

In Xamarin after step 9 third email is displayed in the middle. On the left would be second email and on the right fourth email, but in Maui CollectionView moves to fourth email.

My XAML:

```
<cards:CarouselView 
            x:Name="Carousel"
            ItemsSource="{Binding Emails}"
            IsVerticalSwipeEnabled="False"
            IsCyclical="False"
            IsViewReusingEnabled="False"
            DesiredMaxChildrenCount="3"
            VerticalSwipeThresholdDistance="0"
            IsAutoNavigatingAnimationEnabled="False"
            ItemAppeared="ItemAppeared">

            <cards:CarouselView.ItemTemplate>
                <DataTemplate>
                    <ctrl:EmailView/>
                </DataTemplate>
            </cards:CarouselView.ItemTemplate>
        </cards:CarouselView >
```

Code which add emails:

```
public void LoadMore( object index ) 
    {
        _currentEmailId = Emails.ElementAt( (int)index ).emailId;

        var e = ListItemDetails.FromEmail( _emailSource.JsonEmail );
        RecentsLog.AddToLog( e );

        // last 
        if (Emails.Count-1 == (int)index)
        {
            if (!HasNextEmail()) return;
            _addingNext = true;

            if (_nextTask is { IsCompleted: false })
                _nextTask.Wait();

            // load next
            var idx = _emailIdList.IndexOf( _currentEmailId );
            _loadEmailId = _emailIdList.ElementAt( idx + 1 );
            _nextTask = ReloadSource();

            // remove first
            if (Emails.Count > 3)
                Emails.RemoveAt( 0 );
        }
        else if ((int)index == 0)
        {
            // if not first in email id's then add on left
            if (!HasPreviousEmail()) return;
            _addingNext = false;

            if (_nextTask != null && !_nextTask.IsCompleted)
                _nextTask.Wait();

            // load previous
            var idx = _emailIdList.IndexOf( _currentEmailId );
            _loadEmailId = _emailIdList.ElementAt( idx - 1 );
            _nextTask = ReloadSource();

            // remove last
            if (Emails.Count > 3) 
                Emails.RemoveAt( Emails.Count - 1 );
        }
    }
```

LoadMore is called in code behind:

```
    private async void ItemAppeared( PanCardView.CardsView view, PanCardView.EventArgs.ItemAppearedEventArgs args )
    {
        await Task.Delay( 100 );
        _viewModel.LoadMore( args.Index );
    }
```

**Comment by AndreiMisiukevich** [comment]
Hmm, interesting
When you are removing an item try to set carousel.SelectedIndex -=1;

**Comment by dzebas** [comment]
Thank you for a quick reply! Not sure if it was a typo in your suggestion, but setting carousel.SelectedIndex = 1; fixed the issue.
