### ISSUE TITLE
Artifacts on Back Navigation

### ISSUE THREAD

**Issue by reid-kirkpatrick** [AndreiMisiukevich/CardView.MAUI#31]
We're experiencing an issue where when navigating back away from a page that has a carousel there are artifacts overlayed on the previous page.

Steps to reproduce using the sample
- Tap the "Navigate" button to go to the carousel page
- Swipe to the 2nd page
- Navigate back
- Observe the artifacts

https://github.com/user-attachments/assets/5de1f5c9-3675-4c7b-b762-7084dd8d29ff

[CarouselBlanks.zip](https://github.com/user-attachments/files/16501761/CarouselBlanks.zip)

This does not happen with the MAUI carousel if that's helpful for any reason. Debug vs release doesn't seem to matter either.

**Comment by DashTheDev** [comment]
Just for anyone that might look into this. I had a quick play this morning and can only recreate this issue on MacCatalyst and iOS. Android is working fine.

I can look into fixing this issue after work, but if anyone wants to address before hand just let me know!

**Comment by AndreiMisiukevich** [comment]
Hey, thanks for the report.
Yep, it's an old bug (I think it was happening in Xamarin too)

Thanks @DashTheDev ! <3 
We can try to set Opacity to 0 when Handler (Renderer) is not set

**Comment by reid-kirkpatrick** [comment]
This looks to be fixed in 1.0.0! Thank you so much for the prompt fix @DashTheDev & @AndreiMisiukevich!!!
