### ISSUE TITLE
iOS Crashes using SlideShowDuration

### ISSUE THREAD

**Issue by rmorin04** [AndreiMisiukevich/CardView.MAUI#33]
App sometime crashes when using SlideShowDuration, the CarouselView seems to be scrolling even though the carousel is not visible.

Exception Stack:
System.ArithmeticException: Function does not accept floating point Not-a-Number values.
  at System.Math.Sign(Double value)
  at PanCardView.Processors.CarouselProcessor.GetTranslationX(View view, CardsView cardsView)
  at PanCardView.Processors.CarouselProcessor.Navigate(CardsView cardsView, ProcessorItem[] items)
  at PanCardView.CardsView.<TryAutoNavigate>b__285_1()
  at PanCardView.CardsView.InvokeOnMainThreadIfNeededAsync(Func`1 action)
  at PanCardView.CardsView.TryAutoNavigate()
  at PanCardView.CardsView.ForceRedrawViews()
  at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

**Comment by AndreiMisiukevich** [comment]
@DashTheDev would you like to become a maintainer and help with this project on a constant basis?

**Comment by DashTheDev** [comment]
> @DashTheDev would you like to become a maintainer and help with this project on a constant basis?

Sure! I've been a bit busy with work lately. But I can definitely find time to help out where I can

If a PR isn't made for this by tomorrow, I'll create one and see if if fix works

**Comment by DashTheDev** [comment]
Hey @rmorin04, would it be possible for you to provide a reproducible project please? I did attempt to recreate the crash but no luck. Seeing as you said it sometimes happens, I don't think I'll get there without a use case.

The NaN check proposed by @AndreiMisiukevich will definitely combat that crash, but unsure if there'll be further related crashes. If we can't recreate, I'll just create a PR with the NaN guard and possibly pause slideshows while carousel is not visible.

On that note, @AndreiMisiukevich, do you think we should stop/pause slideshows if the carousel isn't visible? I think it makes sense, would save extra processing. But I'm curious to know if there would be any unintended side effects that you might have come across during development and/or the Xamarin version?

**Comment by AndreiMisiukevich** [comment]
@DashTheDev, IMHO, it's a great idea, but how are you going to check whether the carousel is visible?

For example, it can be hidden by an overlay view or inside a scroll view and not visible on the screen.
Or do you mean just isVisible property? If so, I agree with the proposal

**Comment by AndreiMisiukevich** [comment]
@DashTheDev hey man, do you have a telegram? Don't you mind having a direct personal contact? If it's interesting for you for sure :)

**Comment by DashTheDev** [comment]
> @DashTheDev, IMHO, it's a great idea, but how are you going to check whether the carousel is visible?
> 
> 
> 
> For example, it can be hidden by an overlay view or inside a scroll view and not visible on the screen.
> 
> Or do you mean just isVisible property? If so, I agree with the proposal

Yeah, there's too many factors to account for if we were to try a true detection. So to agree with you, I think just detecting if 'IsVisible == false' or 'Opacity <= 0' will be enough. Then it's completely up to the developer to control over when it's hidden and paused.

Sure, I'll send you an email!

**Comment by AndreiMisiukevich** [comment]
v1.0.1

@DashTheDev thanks as usual
