### ISSUE TITLE
Blank page when navigating back to CarouselView

### ISSUE THREAD

**Issue by dzebas** [AndreiMisiukevich/CardView.MAUI#35]
Hi,

Not sure what is going on, but looks like v1.0.1 broke CarouselView, previous version 1.0.0 works fine.

I've this XAML, nothing special:

```
 <cards:CarouselView 
            x:Name="Carousel"
            ItemsSource="{Binding Emails}"
            IsVerticalSwipeEnabled="False"
            IsCyclical="False"
            IsViewReusingEnabled="False"
            DesiredMaxChildrenCount="3"
            VerticalSwipeThresholdDistance="0"
            IsAutoNavigatingAnimationEnabled="False"
            ItemAppeared="ItemAppeared">

            <cards:CarouselView.ItemTemplate>
                <DataTemplate>
                    <ctrl:EmailView/>
                </DataTemplate>
            </cards:CarouselView.ItemTemplate>
        </cards:CarouselView >
```

In my view model if I push another page and then go back from this page then CarouselView displays blank page. Been using your component since Xamarin.Forms and never had this problem, any ideas?

Thanks in advance!

**Comment by DashTheDev** [comment]
Hey, quite possible. May be some unexpected behaviour with the `DisconnectHandler();` that was added. Which platform is this happening on?

**Comment by dzebas** [comment]
Hi, only tested iOS for now.

**Comment by DashTheDev** [comment]
Okay thanks. I'll have a play and see what's causing it. In theory the disconnect/unload code for the view shouldn't be called until the page is completely out of the navigation stack, so if it's what I think it is, I'll start there.

Are you using Shell or NavigationPages for navigation?

**Comment by dzebas** [comment]
Hi, using Shell. Thanks for super quick response!

**Comment by DashTheDev** [comment]
Hey! PR with fix is out, pending approval. I was trying to be smart and release the resources/memory when the view was _"destroyed"_. But as you know (I've seen you active in the issues surrounding view life cycle), there's currently no real way to do that with the base framework. Excited for [.NET 9 MAUI](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview7/dotnetmaui.md#new-handler-disconnect-policy), fingers crossed it solves our problems!

**Comment by dzebas** [comment]
Thank you so much, really appreciate such a quick turnaround!
