### ISSUE TITLE
TargetFramework net7.0 is required for unit testing

### ISSUE THREAD

**Issue by gabsamples6** [AndreiMisiukevich/CardView.MAUI#4]
Hi,
We have few Maui Class libraries where we have views and view models, we just found that that we cannot test any viewModels where you nuget is referenced , this is because is missing the net7.0 int the target framework.

This is stopping us from doing any kind of ViewModel testing. Would be ok for you to add this and republish your nuget?

**Current**
`<TargetFrameworks>net7.0-ios;net7.0-android;net7.0-maccatalyst</TargetFrameworks>`

**Fix**
`<TargetFrameworks>net7.0;net7.0-ios;net7.0-android;net7.0-maccatalyst</TargetFrameworks>`

many thanks

**Comment by AndreiMisiukevich** [comment]
I think you can use source code for now... because it seems maui requires xCode 13.3, while I am on the latest stable one 14.2

**Comment by gabsamples6** [comment]
Hi thanks for replying... we will use cardView as source code till you manage to sort out - 

Maui - so many niggling issue here and there and  my view is  Maui is buggy but Visual studio is a nightmare at the moment the tooling is not up to scratch.....

and workloads another nightmare - cant wait till we are back to nugets!!

**Comment by AndreiMisiukevich** [comment]
@gabsamples6 Yeah, I know... Forms were far from ideal, but they were much more stable.

**Comment by Hottemax** [comment]
@AndreiMisiukevich just chiming in to say we have the exact same issue, any chance you can publish with `net7.0` ?
Thanks for the library!

**Comment by AndreiMisiukevich** [comment]
v0.0.4
