### ISSUE TITLE
IsCyclical=False causes ItemTemplate to not appear

### ISSUE THREAD

**Issue by nvgogh** [AndreiMisiukevich/CardView.MAUI#40]
Hey

I observe two things

First:
```
<cards:CarouselView ItemsSource="{Binding Tests}" IsCyclical="True">
    <cards:CarouselView.ItemTemplate>
        <DataTemplate>
            <ContentView>
                <Label Text="Test"/>
            </ContentView>
        </DataTemplate>
    </cards:CarouselView.ItemTemplate>
</cards:CarouselView>
``` 
I have the above code snippet in my xaml contentpage. When IsCyclical="True" (I know it's the default for a carousel) then the DataTemplate is rendered on screen. However if IsCyclical="False" the DataTemplate is not rendered. (Also not when I use the CardsView)

Second:
For the life of me, I can't get it to swap item. It always jumps back to the last item of the Tests array. I can see the other items when swiping but then it bounces back to the last item of the array.

Could it be because I am running .net9 ?

Both Android and iOS show the same behavior.

I really want to use your control because it's the first one which sizes correctly.

Thank you 

Natalie

**Comment by AndreiMisiukevich** [comment]
Oh... can you test it on .net8 please?
.net9 can be a root cause...

**Comment by nvgogh** [comment]
I build the project in Net8 (with the 8.* maui libraries) and both issues are there also.

**Comment by AndreiMisiukevich** [comment]
Interesting. I swear it worked just fine in my samples. Including IcCyclical=False

May I ask you to clone this repo and run a sample with either .net8 or .net9?

**Comment by AndreiMisiukevich** [comment]
CC @DashTheDev

**Comment by DashTheDev** [comment]
Hi @nvgogh, I've had a quick play to see if I can replicate this and unfortunately, I wasn't able to. IsCyclical and item switching is working fine on all the scenarios I've tried.

Would you be able to provide a minimal reproducible project please? As soon as I've got that I'll dig deeper into this one. 😄
