### ISSUE TITLE
🧟‍♂️ Is this library a zombie or just taking a power nap? 💤

### ISSUE THREAD

**Issue by AvgustPol** [AndreiMisiukevich/CardView.MAUI#5]
Hey there, @AndreiMisiukevich 

First of all, I just wanted to say that your library is fantastic and has been an invaluable tool. Thank you for your hard work! 🙌

Are you planning to continue developing and maintaining this library in the future? 

Looking forward to hearing from you, and once again, thank you for all the great work you've done! 😊

Best regards,
Anton Vlasiuk

**Comment by AndreiMisiukevich** [comment]
Hi @AvgustPol, thanks for messaging me.
I'd say 🧟‍♂️  but not 100% sure

**Comment by AndreiMisiukevich** [comment]
But if you have interest in this project and want to become a collaborator, I can share collaborator's permission with you

**Comment by AvgustPol** [comment]
Your quote 
"But if you have interest in this project and want to become a collaborator, I can share collaborator's permission with you"

@AndreiMisiukevich let me discuss this with my team, but I can clearly say that this sounds really interesting so far

**Comment by AndreiMisiukevich** [comment]
v0.0.4
