### ISSUE TITLE
[Question] CardView auto height

### ISSUE THREAD

**Issue by eyeveye** [AndreiMisiukevich/CardView.MAUI#8]
Hi, 

For some reason I need to define the height request for the CardView content. It is not automatically expand the height according to the content. 
If someone know how to do it, let me know.

**Comment by AndreiMisiukevich** [comment]
@eyeveye  I think it's a Maui issue.
Can you check the same example with the latest Xamarin.Forms?
If it works, it's MAUI bug (Unfortunately, MAUI is still raw and buggy)
