### ISSUE TITLE
Allow multiple cards to be displayed in carousel when device is rotated horizontally

### ISSUE THREAD

**Issue by bikotoru** [AndreiMisiukevich/CardView.MAUI#9]
I was wondering if it's possible to configure the carousel to display more than one card when the user rotates their device horizontally. Currently, the carousel only displays one card at a time, but I think it would be more user-friendly to take advantage of the extra horizontal space available when the device is rotated.

**Comment by AndreiMisiukevich** [comment]
@bikotoru yes, please use coverflowview instead and setup it properly

**Comment by bikotoru** [comment]
can you send me a example please

**Comment by AndreiMisiukevich** [comment]
@bikotoru https://github.com/AndreiMisiukevich/CardView.MAUI/blob/main/PanCardViewSample/PanCardViewSample/Common/Views/CoverFlowSampleXamlView.xaml
